# Generated by Django 5.2.4 on 2025-08-11 13:48

import django.core.validators
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cover_letter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='desired_hourly_wage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(help_text='A valid email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='employment_type',
            field=models.CharField(choices=[(None, '--Please choose--'), ('ft', 'Full-time'), ('pt', 'Part-time'), ('contract', 'Contract work')], max_length=10),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='start_date',
            field=models.DateField(help_text='The earliest date you can start working.', validators=[jobs.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='website',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
