# Generated by Django 5.2.4 on 2025-08-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_applicant_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, help_text='PDFs Only', upload_to='private/resumes'),
        ),
    ]
